# Generate and return carepackage

- hosts: localhost
  tasks:
  - name: Generate Carepackage
    shell: |
        grep -r . | sed s/:/\\t/ | awk 'BEGIN{FS=OFS="\t"} {gsub(/\//, "\t", $1)} 1' | \
        jq -s --raw-input 'split("\n") | .[0:-1] | map(split("\t")) | 
          map ({"type": .[0], "host_or_domain_name": .[1], "username": .[2], "password": .[3]}) |
            group_by(.type, .host_or_domain_name) | map({ 
              type: (.[0].type), 
              host_or_domain_name: (.[0].host_or_domain_name),
              users: [ .[] | { 
                username: .username, 
                password: .password } ]}) ' | \
        tee ~/carepackage.json
    args:
      chdir: "~/credentials"
    register: carepackage

  - name: "################ Environment Carepackage ################"
    debug:
      var: carepackage.stdout
