output "Management_Server" {
    value = "${module.management_server.details}"
}

output "Lab_Systems" {
    value =  "${module.ansible_inventory.systems}"
}

output "Public_Lab_Systems" {
    value =  "${module.ansible_inventory.Public_Lab_Systems}"
}

output "Carepackage" {
    value = {
        "INFO" = <<EOF
Information about lab-specific account credentials, including the autogenerated ones, is included in the '[Environment Carepackage]',
which is printed oput to screen slighly above this output message.
The carepackage is also available on the management server at ~/carepackage.json"
EOF
    }
}

output "Management_Credentials" {
    value = {
        "Management Ubuntu Username" = "ubuntu"
        "Management macOS Username" = "ec2-user"
        "Management Ubuntu/macOS SSH Key" = "../../SSH-Keys/${terraform.workspace}-management_key.pem"
        "Management Windows Username" = "administrator"
        "Management Windows Password" = nonsensitive(random_password.system_password.result)
    }
}

output "Candidate_Credentials" {
    value = {
        "Kali Candidate Username" = "kali"
        "Kali Candidate SSH Key" = "../../SSH-Keys/${terraform.workspace}-candidate_key.pem"        
    }
}